# Generated by Django 3.2.4 on 2021-08-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210817_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='book', to='books.Book'),
        ),
    ]
